services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - "./backend/app/data:/app/data"
    restart: "unless-stopped"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: "unless-stopped"

   prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml"
    depends_on:
      - backend
    restart: "unless-stopped"

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    restart: "unless-stopped"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana_data:/var/lib/grafana"
    depends_on:
      - prometheus
    restart: "unless-stopped"
